---
title: Bibliography style for AJHG 
date: 2017-10-04
tags: ["latex"]
---

I couldn't find an up-to-date/working **LaTeX bibliography style for the American Journal of Human Genetics (AJHG)**.
The output from `unsrtnat` (my goto style) was also quite different from what the journal wanted.

I found a bibliography style for *Cell* which is almost what AJHG wants, but I also wanted the references to be **ordered by their appearance in the text** (like for `unsrtnat`) and not alphabetically
So I downloaded both `cell.bst` ([here](https://www.ctan.org/tex-archive/macros/latex/contrib/cell)) and `unsrtnat.bst` ([here](https://www.ctan.org/tex-archive/macros/latex/contrib/natbib/)) files and merged them.
I don't understand all the details but after some trial and errors it seems to work.

In addition to the merging I removed the *emphasis* on the Journal/Book name which was the only difference I could see between the Cell and AJHG styles.

I also added some code to **automatically compress long author lists** into "*et al.*".
In the code, the line with `max.num.names.before.forced.et.al` specifies the maximum number of authors before switching to "*et al.*".
The line with `num.names.shown.with.forced.et.al` specifies how many authors to show when using *et al.*.
They are both set at 10, following AJHG guidelines.

The final `ajhg.bst` file can be found [here](https://github.com/jmonlong/Hippocamplus/blob/config/LaTeX/ajhg.bst). I used it with `\usepackage[comma,super]{natbib}`.
