---
title: Journals comparison
date: 2017-10-15
tags: ["pub"]
draft: true
---

Some info about journals in my field.

## Summary table


| Journal                         | Co.   |   IF | OA      | APC      | Other fees   | Pub/year | Received-to-accepted in days. median (75th perc.) |
| ---                             | ---   |  --- | ---     | ---      | ---          | ---      | ---                                               |
| [F1000Research](https://f1000research.com/for-authors/publish-your-research)              | -     |  1.2 | Y       | 1000 USD | -            |          |                                                   |
| [PeerJ](https://peerj.com/about/author-instructions/)                      | -     |  2.2 | Y       | 1095 USD | -            | ~1290    | ~88 (139)                                         |
| [eLife](https://submit.elifesciences.org/html/elife_author_instructions.html#process)                      | -     |  7.8 | Y       | 2500 USD | -            | 1018     | 121 (155)                                         |
| [GigaScience](https://academic.oup.com/gigascience/pages/instructions_to_authors)                | OUP   |  4.9 | Y       | 2050 USD | -            | ~50      | ~126 (195)                                        |
| [PLoS One](http://journals.plos.org/plosone/s/criteria-for-publication)                   | PLoS  |  2.8 | Y       | 1495 USD | -            | ~22K     | ~122 (182)                                        |
| [PLoS Comp Bio](http://journals.plos.org/ploscompbiol/s/journal-information)              | PLoS  |  4.5 | Y       | 2250 USD | -            | ~550     | ~159 (217)                                        |
| [PLoS Genetics](http://journals.plos.org/plosgenetics/s/journal-information)              | PLoS  |  6.1 | Y       | 2250 USD | -            | 644      | 150 (202)                                         |
| [PLoS Biology](http://journals.plos.org/plosbiology/s/journal-information)               | PLoS  |  9.8 | Y       | 2900 USD | -            | ~176     | ~141 (175)                                        |
| [BMC Bioinformatics](https://bmcbioinformatics.biomedcentral.com/submission-guidelines)         | BMC/S |  2.5 | Y       | 2145 USD | -            | ~333     | ~169 (231)                                        |
| [BMC Genomics](https://bmcgenomics.biomedcentral.com/submission-guidelines)               | BMC/S |  3.7 | Y       | 2145 USD | -            | ~985     | ~138 (190)                                        |
| [BMC Biology](https://bmcbiol.biomedcentral.com/submission-guidelines)                | BMC/S |  6.8 | Y       | 2785 USD | -            | ~85      | ~70 (108)                                         |
| [Genome Biology](https://genomebiology.biomedcentral.com/submission-guidelines)             | BMC/S | 11.9 | Y       | 2975 USD | -            | ~156     | ~106 (143)                                        |
| [Cell Reports](http://www.cell.com/cell-reports/authors)               | Els   |  8.3 | Y       | 5000 USD | -            | ~1005    | ~168 (241)                                        |
| [Scientific Reports](https://www.nature.com/srep/publish/guidelines)         | Spr   |  4.3 | Y       | 1760 USD | -            | ~20K     | ~104 (151)                                        |
| [Nature Communications](https://www.nature.com/ncomms/submit/guide-to-authors)      | Spr   | 12.1 | Y       | 5200 USD | -            | ~3519    | ~168 (228)                                        |
| [NAR](https://academic.oup.com/nar/pages/Policies)                        | OUP   | 10.2 | Y       | 2770 USD | pp9          | ~1359    | ~82 (131)                                         |
| [Genetics](http://www.genetics.org/content/prep-manuscript)                   | -     |  4.6 | 12m/+   | 2000 USD | pp/pf/psf    | ~374     | ~104 (163)                                        |
| [AJHG](http://www.cell.com/ajhg/authors)                       | Els   |  9.0 | 6m/+    | 5000 USD | 850 USD + pf | 237      | 89 (121)                                          |
| [PNAS](http://www.pnas.org/page/authors/submission)                       | HWP   |  9.7 | 6m/+    | 1450 USD | 1700 USD     |          |                                                   |
| [Genome Research](http://genome.cshlp.org/site/misc/ifora.xhtml)            | CSH   | 11.9 | 6m/+    | 2500 USD | 2500 USD     | ~179     | ~188 (242)                                        |
| [Cell](http://www.cell.com/cell/authors)                       | Els   | 30.4 | (12m/+) | 5000 USD | pf           | ~351     | ~149 (193)                                        |
| [Lancet](http://www.thelancet.com/lancet/information-for-authors)                     | Els   | 47.8 | 6m/+    | 5000 USD |              |          |                                                   |
| [Science](http://www.sciencemag.org/authors/science-journals-editorial-policies)                    | AAAS  | 37.2 | 12m     | -        | surprise     | ~720     | ~112 (162)                                        |
| [Bioinformatics](https://academic.oup.com/bioinformatics/pages/instructions_for_authors)             | OUP   |  7.3 | +       | 3000 USD | pp7/pf       | ~868     | ~126 (180)                                        |
| New England Journal Of Medicine | -     | 72.4 | 6m      | -        |              |          |                                                   |
| [Nature Methods](https://www.nature.com/nmeth/for-authors)_            | Spr   | 25.1 | N       | -        | pf           | ~130     | ~146 (187)                                        |
| [Nature Genetics](https://www.nature.com/ng/for-authors)            | Spr   | 28.0 | N       | -        | pf           | 202      | 147 (203)                                         |
| [Nature Biotech](https://www.nature.com/nbt/for-authors)             | Spr   | 41.7 | N       | -        | pp5/pf       | 80       | 202 (262)                                         |
| [Nature](https://www.nature.com/nature/for-authors)                     | Spr   | 40.1 | N       | -        |              | ~855     | ~175 (246)                                        |

Open Access (OA) journal:

- `Y`: Yes.
- `+`: Authors can pay additional Article Processing Charges (column APC) to make it accessible immediately upon publication.
- `12m`: Articles are accessible after 12 months, either from the journal or [PubMed Central](https://www.ncbi.nlm.nih.gov/pmc/)/
- `6m`: Articles are accessible after 6 months, either from the journal or [PubMed Central](https://www.ncbi.nlm.nih.gov/pmc/).
- `()`: Depending on the funding agencies.
- `N`: No.

Fees:

- `pp`: Per page.
- `ppX`: Per page in excess of X (if more than X pages).
- `pf`: Per figure.
- `psf`: Per supplementary file.

## Sources

- Impact Factor for 2016/2017 from [bioxbio](http://www.bioxbio.com/if/).
- APC from [Directory of Open Access Journals](https://doaj.org/), or the journal.

*Received-to-accepted time* and *Pub/year* are based on articles published in 2016. After a PubMed search, the publication page was crawled to get the article type and dates of reception/acceptance. Only research articles/letters are considered (no method/tools/resource/editorial/perspective/erratum/opinion/...). Sometimes the DOI was not present in the PubMed results or there was a lot a publications to crawl so I analyzed a subset and extrapolated the numbers (`~` marks approximated numbers). I still see some suspicious numbers (articles with very short/negative acceptance time). Hopefully the medians are still close to reality but these numbers should be taken with a grain of salt.

## Median time to acceptance/publication

```{r, echo=FALSE, message=FALSE, fig.width=10}
library(ggplot2)
library(dplyr)
library(tidyr)

load("../../data/journalComp.RData")
art.types = c('Article','Research Article','Research article', 'Research', 'PEER-REVIEWED', 'INVESTIGATIONS','Feature Article','Meta-Research Article')
meth.types = c('Methodology article','Methodology Article', 'METHOD', 'Method','Methodolgy article')
letter.types = c('Letter', 'Brief Communication')
report.types = c('Registered Report', 'Report', 'Short Report', 'Technical Report')

pub.s = pub.df %>% filter(type %in% c(art.types, meth.types, letter.types, report.types)) %>% group_by(journal) %>% summarize(n=sum(ss), ra=median(ra, na.rm=TRUE), rp=median(rp, na.rm=TRUE)) %>% gather(type,days, -n, -journal) %>% mutate(type=factor(type, levels=c('ra','rp'),labels=c('accepted', 'published')), pubs=cut(n, c(0,300,1000,2e4,Inf), labels=c('<300','300-1000','1000-20K','>20K')))
## ggplot(pub.s, aes(x=reorder(journal,days, min), y=days, colour=type, size=pubs)) + geom_point() + theme_bw() + theme(axis.text.x=element_text(angle=90, hjust=1, vjust=.5), legend.position=c(.99,.01), legend.justification = c(1,0), legend.box='horizontal') + scale_y_continuous(breaks=seq(0,max(pub.s$days),25), limits=c(0,max(pub.s$days))) + xlab('') + ylab('median time (days)') + scale_colour_brewer(palette='Set1', name='received to', direction=-1) + scale_size_manual(name='research article/year', values=c(2,4,6)) + guides(colour = guide_legend(override.aes = list(size=3)))

ggplot(pub.s, aes(x=reorder(journal,days, min), y=days)) + geom_point(aes(colour=type, size=pubs)) + theme_bw() + geom_hline(yintercept=0) + 
  theme(legend.background = element_rect(colour='black'),
      ##axis.text.x=element_text(angle=90, hjust=1, vjust=.5),
      legend.position=c(.01,.99), legend.justification = c(0,1), legend.box='horizontal',, axis.text.x=element_blank()) + scale_y_continuous(breaks=seq(0,max(pub.s$days),25), limits=c(0,max(pub.s$days))) + xlab('') + ylab('median time (days)') + scale_colour_brewer(palette='Set1', name='received to', direction=-1) + scale_size_manual(name='research articles in 2016', values=c(2,4,6,9)) + guides(colour = guide_legend(direction='horizontal', override.aes = list(size=3)), size=guide_legend(direction='horizontal')) + geom_text(aes(label=journal), data=subset(pub.s, type=='accepted'), angle=90, hjust=1, nudge_y = -8)
```

## "Good" journals

- [eLife](https://elifesciences.org/) is non-profit, open and modern.
- [PLOS](https://www.plos.org/which-journal-is-right-for-me) the pioneer in open-access.
- [BMC](http://www.biomedcentral.com/p/the-bmc-series-journals#journallist), although it's owned by Springer Nature publishing group.
- [F1000](https://f1000research.com/) where the manuscript is "published" right away and then transparently peer-reviewed. Once peer-reviewed, it is indexed in PubMed etc.
- [PeerJ](https://peerj.com/) is about open-access and cost-efficient publishing.

## "Evil" publishing companies

- Elsevier.
- Springer Nature.

## Further reading

- [Does it take too long to publish research? (Nature News Feature)](http://www.nature.com/news/does-it-take-too-long-to-publish-research-1.19320)
- ["Why I still won’t review for or publish with Elsevier–and think you shouldn’t either" by Tal Yarkoni](https://www.talyarkoni.org/blog/2016/12/12/why-i-still-wont-review-for-or-publish-with-elsevier-and-think-you-shouldnt-either/)
