---
title: Repeat Masker exploration
date: 2016-06-04
tags: ["genome"]
draft: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.width=8)
```

```{r libs}
library(ggplot2)
library(dplyr)
library(magrittr)
library(knitr)
library(GenomicRanges)
library(rtracklayer)
library(waffle)
library(RColorBrewer)
## library(ggrepel)
library(PopSV)
library(data.table)
winsor <- function(x,u=10){
    if(any(x>=u)) x[x>=u] = u
    x
}
olBins <- function(bins.df, feat.df, label="ol"){
  bins.gr = makeGRangesFromDataFrame(bins.df)
  feat.gr = makeGRangesFromDataFrame(feat.df)
  res.df = data.frame(n=rep(0,nrow(bins.df)), d=rep(0,nrow(bins.df)))
  colnames(res.df) = paste(label,colnames(res.df), sep=".")
  res.df[,1] = countOverlaps(bins.gr, feat.gr)
  feat.gr = reduce(feat.gr)
  ol = findOverlaps(bins.gr, feat.gr) %>% as.data.frame %>% mutate(qsw=width(pintersect(bins.gr[queryHits], feat.gr[subjectHits]))) %>% group_by(queryHits) %>% summarize(bp=sum(qsw))
  res.df[ol$queryHits,2] = ol$bp
  res.df[,2] = res.df[,2] / width(bins.gr)
  bins.df = cbind(bins.df, res.df)
  bins.df
}
library(BSgenome.Hsapiens.UCSC.hg19)
seql.1.22 = seqlengths(BSgenome.Hsapiens.UCSC.hg19)[paste0("chr",1:22)]
rand.gr <- function(widths){
    chrs = apply(rmultinom(length(widths), 1, (seql.1.22/1e3)/sum(seql.1.22/1e3)),2,function(e)which(e==1))
    starts = runif(length(widths), 0, seql.1.22[chrs]-widths)
    return(GRanges(chrs, IRanges(starts, width=widths)))
}
```

## Repeat Masker

```{r dl}
if(!file.exists("rmsk.txt.gz")) download.file("http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz","rmsk.txt.gz")
rm.df = as.data.frame(fread("gunzip -c rmsk.txt.gz", showProgress = FALSE, sel=c(6:8, 11:13)))
colnames(rm.df) = c("chr","start","end","repName","repClass","repFamily")
rm.df %<>% mutate(chr=gsub("chr","",chr)) %>% filter(chr %in% c(1:22, "X", "Y"))
rm.gr = makeGRangesFromDataFrame(rm.df)
if(!file.exists("genomicSuperDups.txt.gz")) download.file("http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/genomicSuperDups.txt.gz", "genomicSuperDups.txt.gz")
sd = read.table('genomicSuperDups.txt.gz', as.is=TRUE)
sd = sd[,c(2:4,8:10,27)]
colnames(sd) = c('chr', 'start', 'end', 'chr2', 'start2', 'end2', 'fracMatch')
sd %<>% mutate(chr=gsub("chr","",chr)) %>% filter(chr %in% c(1:22, "X", "Y"))
sd.gr = makeGRangesFromDataFrame(sd)
```

I downloaded Repeat Masker at [http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz](http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz).

```{r ex}
rm.df %>% sample_n(10) %>% kable(row.names=FALSE)
```

The annotation spans a total of `r round(sum(width(reduce(rm.gr))/1e9),2)` Gbp. 
If we include segmental duplication, `r round(sum(width(reduce(c(rm.gr, sd.gr)))/1e9),2)` Gbp are annotated as repeat in the human genome.


### TE Density

Using different window size, how many regions contain a TE ?

```{r tedens}
tes = c("LINE","DNA","SINE","LTR","DNA?","Other","SINE?","LTR?","LINE?")
tes.gr = makeGRangesFromDataFrame(subset(rm.df, repClass %in% tes))
tes.null = rand.gr(width(tes.gr))
sd.gr = makeGRangesFromDataFrame(sd)
sd.null = rand.gr(width(sd.gr))

bins.rep = lapply(c(500,1000,1e4,1e5), function(winsize){
  bins = fragment.genome.hg19(winsize)
  bins$te = overlapsAny(makeGRangesFromDataFrame(bins), tes.gr)
  bins$te.null = overlapsAny(makeGRangesFromDataFrame(bins), tes.null)
  bins$sd = overlapsAny(makeGRangesFromDataFrame(bins), sd.gr)
  bins$sd.null = overlapsAny(makeGRangesFromDataFrame(bins), sd.null)
  data.frame(size=winsize,
             prop=c(mean(bins$te), mean(bins$sd)),
             prop.null=c(mean(bins$te.null), mean(bins$sd.null)),
             rep=c('TE','SD'), stringsAsFactors=FALSE)
})
bins.rep = do.call(rbind, bins.rep)

ggplot(bins.rep, aes(x=factor(size), y=prop, fill=rep)) + geom_bar(stat='identity', position='dodge') + theme_bw() + ylim(0,1)

ggplot(bins.rep, aes(x=factor(size), y=prop/prop.null, fill=rep)) + geom_bar(stat='identity', position='dodge') + theme_bw() + ylim(0,1)


bins = fragment.genome.hg19(1e4)
bins$sd = overlapsAny(makeGRangesFromDataFrame(bins), sd.gr)
mean(bins$sd)


```

### Alpha satellites

```{r alpha}
alpha = subset(rm.df, repName=='ALR/Alpha') %>% makeGRangesFromDataFrame
mean(width(alpha))
```
