---
title: La formation de l'esprit scientifique, Gaston Bacherlard
tags: ["science"]
date: 2018-09-29
draft: true
slug: bachelard-formation-esprit-scientifique
output: blogdown::html_page
---

These are notes from my reading of [*La formation de l'esprit scientifique*](https://fr.wikipedia.org/wiki/La_Formation_de_l%27esprit_scientifique) by [Gaston Bachelard](https://en.wikipedia.org/wiki/Gaston_Bachelard).
I hesitated a bit but finally decided to write the notes in English because in the end this blog is as much a place to save things I want to remember as a place to practice writing in English and share with other people.
There are a lot of quotes that I liked. 
I tried to translate them as best I could.


## Quotes about science

> La connaissance du réel est une lumière qui projette toujours quelque part des ombres.

"Knowledge of reality is a light that always throws shadows somewhere."

---

On seeking knowledge:

> En résumé, l'homme animé par l'esprit scientifique désire sans doute savoir, mais c'est aussitôt pour mieux interroger.

"In summary, the person moved by the scientific spirit surely desires knowledge, but it is to better immediately interrogate." 

---

> En fait, l'histoire des mathématiques est une merveille de régularité. Elle connaît des périodes d'arrêt. Elle ne connaît pas des périodes d'erreurs.

## Epistemological obstacle

This is the central concept of this work.
The obstacle is not external, it is not caused by observed phenomenon that are too mysterious or complex, or technological limitations.
The epistemological obstacle is internal and ideological.
When ideas stagnate or regress, we are facing an epistemological obstacle.

Epistemological obstacle is studied in two settings: the development of scientific thinking throughout history and in the educational practice.

The difference between an historian and an epistemologist is that the historian takes ideas as fact, while the epistemologist takes fact as ideas and place them in a system of thoughts.
Through the notion of epistemological obstacle, the history of scientific thinking gains a spiritual value.

The first experiment/observation is the first epistemological obstacle.
It looks easy to understand or generalize, seducing us into believing that we understand the beauty of nature.
It usually comes with a sense of marvel as it's the first time it's observed or "understood".
We think we understand and that's the obstacle.

The second obstacle is to follow hasty generalizations like the ones that emerge from the first obstacle.

Other obstacles in not particular order:

- Using the unity of Nature as an explanation.
- Using the utility of natural phenomenon as an explanation.
- The verbal obstacle that uses explanatory words.
- Substantialism/realism ?
- "The animist obstacle in physical sciences".
- False geometrization and rigor.

## On the obstacle of close-mindedness

Instincts or opinions contribute to epistemological obstacles.
Similarly education and previous knowledge play a role and a researcher must be able to rethink, to make abstraction of what she thinks is true, when fighting against an epistemological obstacle.


> Accéder à la science, c'est, spirituellement rajeunir, c'est accepter une mutation brusque qui doit contredire un passé.

"To access science is to spiritually rejuvenate, it's accepting an abrupt mutation that must contradict a past."

---

> On ne peut rien fonder sur l'opinion: il faut d'abord la détruire. Elle est le premier obstacle à surmonter.

"We cannot base anything on opinion: it must first be destroyed. It's the first obstacle to overcome."

---

> Les grands hommes sont utiles à la science dans la première moitié de leur vie, nuisibles dans la seconde moitié.

"Great men are useful to science in the first half of their life, harmful in the second half."

--- 

> [...] l'homme devient une espèce mutante, ou pour mieux dire encore, une espèce qui a besoin de muter, qui souffre de ne pas changer.

"Man becomes a mutant species, or better said still, a species that needs to mutate, that suffers of not changing."

---

> Toute culture scientifique doit commencer [...] par une catharsis intelectuelle et affective.

"Any scientific culture must begin with an intellectual and emotional catharsis."

Yes, catharsis of course...*googling*...ah yes, catharsis, that makes sense.


## On trappings of empirical observations

Second obstacle.

> Comme le dit si bien d'Alembert, on généralise ses premières remarques, l'instant d'après qu'on ne remarquait rien.

"Like d'Alembert nicely stated, we generalize our first observations, the moment after we didn't observe anything."

---

> Il est si doux à la paresse intellectuelle d'être cantonnée dans l'empirisme, d'appeler un fait un fait et d'interdire la recherche d'une loi!

## On the danger of images and metaphors

> On remplace la connaissance par l'admiration, les idées par les images.

"We replace knowledge with admiration, ideas with images."

---

On detrimental curiosity (I think):

> Elle cherche non pas la variation, mais la variété.

---

> Une science qui accepte les images est, plus que toute autre, victime des métaphores. Aussi l'esprit scientifique doit-il sans cesse lutter contre les images, contre les analogies, contre les métaphores.

---

> Mieux vaudrait une ignorance complète qu'une connaissance privée de son principe fondamental.

"Complete ignorance would be better than knowledge deprived of its fundamental principle."


## Education

Little effort has been directed toward the study of the psychology of ignorance and error.
People think it's just a matter of giving a lesson, repeating it until it's grasped by the student, often using the same approach each time (e.g. retaking the class).
The problem is that the student already has previous knowledge that impedes the understanding of the "lesson".
So the teacher needs first to break down these obstacles, that come from the student's previous observations, in order to efficiently teach the new concepts.
We spend too much effort on adding new concepts that will not always sort themselves out nicely in the student's mind.
We should spend more time guiding this conceptual readjustments when teaching science.

> Les professeurs de sciences, plus encore que les autres si c'est possible, ne comprennent pas qu'on ne comprenne pas.

"Science teachers, even more than others if that is possible, don't understand that one doesn't understand."

---

> Un educateur n'a pas le sens de l'echec precisement parce qu'il se croit un maitre.

"A teacher doesn't have a sense of failure precisely because he believes himself to be a master."

## Interesting stories

- How people were fascinated by [Leyden jars](https://www.youtube.com/watch?v=xjW-isgOijs).

## Sick burns

> On imagine assez facilement qu'un enfant de huit ans, à la seule condition d'avoir à sa disposition un vocabulaire pédant, pourrait développer de telles billevesées.

"We can imagine quite easily that an eight years old child, if only he had a pedantic vocabulary at his disposal, would develop similar nonsense."
