---
sidebar: true
title: Shell
weight: 1
output:
  blogdown::html_page:
    toc: true
---

## Misc

### Colors in `less`

Use the `-r` or `-R` option. Sometimes the previous command needs a parameter make sure the output includes color codes.

~~~sh
tree -C | less -R
ls --color | less -R
grep --color=always | less -R
~~~

### Avoid killing ssh jobs

`nohup` function (apparently).

### rsync

`rsync` is not completely intuitive to me. 
Here are some of the commands I could make work.

--- 

To recurrently sync all the files that match the patterns in `rsyncIncludes.txt`:

~~~sh
rsync -r --include='*/' --include-from=rsyncIncludes.txt --exclude='*' --prune-empty-dirs SRC DEST
~~~

---

To recurrently sync all the files that match the patterns in `rsyncIncludes.txt` EXCEPT some with a specific pattern.
Practical example: all the R scripts but not the ones created by BatchJobs in `*-files` directories:

~~~sh
rsync -r --exclude="*-files" --include='*/' --include='*.R' --exclude='*' --prune-empty-dirs SRC DEST
~~~

## One-liners

### Add headers with cat

`cat file.txt | cat headers.txt -` concatenated end of the pipe after `headers.txt`.

### Remove empty directories

`find . -type d | xargs rmdir`

### AWK

- Capture group in string regexp using `match($0, /xxx(.*)yyy/, a); print a[1]'`

### Perl one-liners

Inspired from these: [Catonmat](http://www.catonmat.net/blog/introduction-to-perl-one-liners/), [Ksplice](https://blogs.oracle.com/ksplice/the-top-10-tricks-of-perl-one-liners)

- `-p` run command on each line and print line.
- `-n` run command on each line but don't print line.
- `-i` operates on the file in-place, i.e. updating the input file.
- `-a` split the lines by white spaces into a `@F` array (`-F` to choose the separator)
- `-l` removes the trailing new line, and adds it back if `-p` is used.
- `$_` contains the line.
- `$.` contains the line number.

- Replace text line-by-line in a file: `perl -pe 's/you/me/g'`
- Replace text if line contains *foo*: `perl -pe 's/you/me/g if /foo/`
- Replace text line-by-line with regexp: `perl -pe 's/ID(\d+)/$1/g'`
- Operations on a CSV file: `perl -F, -ane 'print $F[3]+$F[8]`
- Operations on a CSV file and print at the end: `perl -F, -ane $t+=$F[3]+$F[8]; END{print $t}`
- Print matches from regular expression: `perl -ne 'print "$1\n" if /foo=([^;]*)/'`

## Shell scripting

Start a script with one of the [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29)

~~~sh
#!/bin/sh
~~~

### Variables

To remove a specific prefix/suffix from a variable name:

~~~sh
foo=${foop#$prefix}
foo=${foos%$suffix}
~~~

### If Then Else

A simple example:

~~~sh
if [ $VAL == "YEP" ]; then
	echo "It's a yes!"
else
	echo "No no no :("
fi
~~~

Or with multiple conditions:

~~~sh
if [ $VAL == "YEP" ] && [ COND ]; then
	echo "It's a yes!"
else
	echo "No no no :("
fi
~~~

The spacing is quite important, and the conditions can be built with:

+ `-eq` equal to.
+ `-ne` not equal to.
+ `-lt` less than.
+ `-le` less or equal than.
+ `-gt` great than.
+ `-ge` great or equal than.
+ `-s` file exists and not empty.
+ `-f` file exists and not directory.
+ `-d` directory exists.
+ `-x` file executable.
+ `-w` file writable.
+ `-r` file readable.


## Convert PDF 

### to EPS

I ended up using Inkscape in command-line mode. The result is not so bad (better than the `pdf2eps` etc).

~~~sh
inkscape document.pdf --export-eps=document.eps
~~~

[Apparently](http://blm.io/blog/convert-pdf-eps-osx/), `pdftops` is even better.

~~~sh
pdftops -eps document.pdf
~~~

### to PDF/A

In the end I had to use Acrobat Reader Pro...
Still, converting the PDF using the following commands beforehand helped (otherwise Acrobat Reader Pro couldn't convert it):

~~~sh
gs -dPDFA=1 -dBATCH -dNOPAUSE -dEmbedAllFonts=true -dSubsetFonts=false -dHaveTrueTypes=true -dPDFSETTINGS=/prepress -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -sPDFACompatibilityPolicy=1 -sOutputFile=mainPDFA.pdf main.pdf
~~~

On the other hand, passing by a `.ps` stage as recommended [here](https://superuser.com/questions/188953/how-to-convert-a-pdf-to-a-pdf-a), produced a smaller PDF that was directly PDF/A compliant (no need for Acrobat Reader Pro) but lost all cross-reference links :(

~~~sh
pdftops main.pdf main.ps
gs -dPDFA -dBATCH -dNOPAUSE -dNOOUTERSAVE -dUseCIEColor -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -sPDFACompatibilityPolicy=1 -sOutputFile=mainPDFA.pdf main.ps
~~~

To check for PDF/A compliance I used [this online validator](https://www.pdf-online.com/osa/validate.aspx) or Acrobat Reader Pro.
Another way to check for problems is to look at the *emb* column of `pdffonts main.pdf` (should be all embedded) and the *type* column of `pdfimages -list main.pdf` (should be all *image*).

*Note: this is based only on my one-time experience with the PDF of my thesis.*

## Git

+ Commit all modification and added files: `git commit -am "informative message"`
+ To show all the history of a file: `git log -p -- file`.
+ To retrieve a specific version of a file: `git show COMMIT:file`.
+ Update sub-modules: `git submodule update --init --recursive`

#### Aliases

~~~sh
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.br branch
~~~


#### Branches

+ List branches: `git branch`
+ List all branches: `git branch -a`
+ Update remote branch list: `git remote prune origin`
+ Create branch: `git checkout -b hotfix`
+ Link it to a remote branch: `git branch -u origin/hotflix`
+ Creat a new local branch from remote: `git co -t origin/hotfix`
+ Merge the current branch with another branch: `git merge hotfix`
+ Delete a branch: `git branch -d hotfix`
+ Delete remote branch: `git push origin :hotfix`


#### Check status of all repos

I have an alias calling the following commands:

~~~sh
WD=`pwd`
for ff in `find . -maxdepth 5 -name .git`
do
    GDIR=`dirname $ff`
    echo $GDIR
    cd $WD/$GDIR
    git st -s
    git st | grep ahead
done
cd $WD
~~~


## Docker cheatsheet

I'm still learning Docker but here are commands/parameters that seem relevant for me:

#### Build a docker instance

[Write a Dockerfile](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/) :

+ `WORKDIR /root` sets the working directory.
+ `COPY PopSV_1.0.tar.gz ./` copies a file in the instance. The `/` is important !
+ There is a cache management system so it's important to keep related commands in the same `RUN`.

To run in the folder with the `Dockerfile`.

~~~sh
docker build -t jmonlong/popsv-docker .
~~~

#### Launch a docker instance

To launch an interactive instance with a shared folder:

~~~sh
docker run -t -i -v /home/ubuntu/analysis1:/root/analysis1 jmonlong/popsv-docker
~~~

+ `-t` and `-i` are used for interactive run.
+ `-v` links folder in the host with folder in the image. It must be **absolute paths*.

#### Increase memory

In Mac OS, I had some problems with the docker stopping because of memory issues.
I fixed by changing:

~~~sh
docker-machine stop
VBoxManage modifyvm default --cpus 3
VBoxManage modifyvm default --memory 8192
docker-machine start
~~~

## Makefile

- [Makefile basics from Isaacs](https://gist.github.com/isaacs/62a2d1825d04437c6f08).

## Modules

For example installing Emacs as a module on a HPC.
After installing Emacs locally in a `~/softwares/emacs/emacs-24.4` I create a file `~/myModules/jmonlong/emacs/24.4` with:

~~~shell
#%Module1.0
proc ModulesHelp { } {
  puts stderr "\tMUMmer "
}
module-whatis "mummer"

set             root                /home/jmonlong/softwares/emacs/emacs-24.4
prepend-path    PATH                $root/bin
prepend-path    LIBRARY_PATH        $root/lib/
prepend-path    LD_LIBRARY_PATH     $root/lib/
~~~

Then to use the module:

~~~shell
module use ~/myModules
module load jmonlong/emacs
~~~


## OSX

### Mount server

I created a directory `sftp` (I don't know why I choose this name...anyway) and mount the root of the different servers there. Eventually I created a symbolic link at the root of my computer to point there so that paths like `/gs/projects/...` work directly, as if in the cluster.

To mount a server I use the following command:

~~~sh
sshfs jmonlong@guillimin.hpc.mcgill.ca:/ /Users/jeanmonlong/sftp/guillimin -ovolname=NAME
~~~

### Setup WD Elements external hard drive

By default the disk is formatted in NTFS, which OSX could read only. To write, the solution that worked for me was to add this line to `/etc/fstab`:

~~~sh
LABEL=Elements none ntfs rw,auto,nobrowse
~~~

*Note: If there are spaces in the label, replace them by `\040`.*

The disk can then be accessed through the *Volumes* folder (`/Volumes`).
